### ISSUE TITLE
Visualize analysis

### ISSUE THREAD

**Issue by aclowkey** [o19s/elyzer#19]
I've had this idea ever since my first `GET _analyze` on Kibana dev-tools - why don't we have the tokens visualized?

This could useful for the devs working with Kibana dev-tools.

I've tried creating Kibana plugins on the weekend, seems like no easy fit. If anyone has useful resources that'll be great.

**Comment by softwaredoug** [comment]
Love the idea! I'd advocate for this being a different tool. I would love to see this in Kibana (Solr's admin UI has a very nice analysis UI in case you want inspiration)
