### ISSUE TITLE
Support for built-in analyzers

### ISSUE THREAD

**Issue by consulthys** [o19s/elyzer#4]
It would be nice if some of the built-in analyzers were also supported. Mainly the following ones which don't require any specific configuration:
 * `simple`
 * `whitespace`
 * `keyword`
 * `stop`
 * `standard`
 * `snowball`

**Comment by softwaredoug** [comment]
Should this be closed by #5 or did you want to keep this open to add other analyzers in the future?

**Comment by consulthys** [comment]
I think it is ok to close it for now. I'm thinking about how to add the remaining built-in analyzers, which require some configuration.

**Comment by consulthys** [comment]
Given this change, it would probably be a good idea to update the README page to remove (or reword) the following shortcoming:

> Only works for custom analyzers right now (as it accesses the settings for your index)
